FROM node:16.17.0
WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install -g npm@latest && npm install create-next-app

# FROM  node:16.13.1

# WORKDIR /usr/src/[この辺に何か書く]
# COPY . .
# RUN npm install
# RUN yarn build

# EXPOSE 3000

# CMD ["yarn", "start"] 
