import type { NextPage } from 'next'
import Head from 'next/head';
import axios from 'axios';
import Link from 'next/link';

export async function getServerSideProps() {
    const res = await axios.get(`${process.env.API}:8080/eventGet`, {
    });
    const data = await res.data;
  
    return { 
        props: {
            data: data 
        }
    };
  }
  
  const Home: NextPage = ({data}:any) => {
    console.log(data)
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
          {data[0].Name}
          <Link href={"/"}>
            <h2>HOME</h2>
          </Link>
        </main>
  
      </div>
    )
  }
  
  export default Home