import Head from 'next/head'
// import Header  from './admin-header';
import Footer  from './admin-footer';

export default function Layout({ children }:any) {
    return (
      <>
        <Head>
          <title>スマートGAKUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Header /> */}
        <main>{children}</main>
        <Footer />
      </>
    );
  }